services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - ./data:/data
    networks:
      - app-network
    env_file:
      - ./.env
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}

networks:
  app-network:
    driver: bridge

volumes:
  redis-data: