services:
  valkey:
    image: 'valkey/valkey:latest'
    ports:
      - '6379:6379'
    volumes:
      - ./data:/data
    networks:
      - app-network
    env_file:
      - ./.env
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - VALKEY_DISABLE_COMMANDS=FLUSHDB,FLUSHALL

networks:
  app-network:
    driver: bridge

volumes:
  data:
    driver: local